---
# Source: kommodity-cluster/templates/provider/capi/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: my-cluster-controlplane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: my-cluster
    namespace: default
---
# Source: kommodity-cluster/templates/provider/docker/cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: localhost
    port: 6443
---
# Source: kommodity-cluster/templates/provider/docker/machinetemplate.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: my-cluster-controlplane
  namespace: default
spec:
  template:
    spec:
      customImage: ghcr.io/siderolabs/talos:v1.11.0
---
# Source: kommodity-cluster/templates/provider/docker/machinetemplate.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: my-cluster-worker-default
  namespace: default
spec:
  template:
    spec:
      customImage: ghcr.io/siderolabs/talos:v1.11.0
---
# Source: kommodity-cluster/templates/provider/capi/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: my-cluster-worker-default
  namespace: default
spec:
  clusterName: my-cluster
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: my-cluster-worker-default
          namespace: default
      clusterName: my-cluster
      failureDomain: 
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: my-cluster-worker-default
        namespace: default
      version: v1.33.4
---
# Source: kommodity-cluster/templates/talos/configtemplate.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: my-cluster-worker-default
  namespace: default
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.11.0
---
# Source: kommodity-cluster/templates/talos/controlplane.yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: my-cluster-controlplane
  namespace: default
spec:
  version: v1.33.4
  replicas: 
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: my-cluster-controlplane
    namespace: default
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.11.0
      hostname: {}
    init:
      generateType: init
      hostname: {}
