{{- if eq .Values.kommodity.provider.name "Azure" }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ .Release.Name }}-controlplane-{{ include "kommodity-cluster.machineSpecsHash" (dict "poolValues" .Values.kommodity.controlplane "allValues" .Values) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  template:
    spec:
      vmSize: {{ .Values.kommodity.controlplane.sku }}
      {{- if dig "marketplace" "" .Values.talos }}
      image:
        marketplace:
          publisher: {{ .Values.talos.marketplace.publisher }}
          offer: {{ .Values.talos.marketplace.offer }}
          sku: {{ .Values.talos.marketplace.sku }}
          version: {{ .Values.talos.marketplace.version }}
      {{- else if dig "computeGallery" "" .Values.talos }}
      image:
        computeGallery:
          gallery: {{ .Values.talos.computeGallery.gallery }}
          name: {{ .Values.talos.computeGallery.name }}
          version: {{ .Values.talos.computeGallery.version }}
          {{- if dig "computeGallery" "subscriptionID" "" .Values.talos }}
          subscriptionID: {{ .Values.talos.computeGallery.subscriptionID }}
          {{- end }}
          {{- if dig "computeGallery" "resourceGroup" "" .Values.talos }}
          resourceGroup: {{ .Values.talos.computeGallery.resourceGroup }}
          {{- end }}
      {{- else if dig "id" "" .Values.talos }}
      image:
        id: {{ .Values.talos.id }}
      {{- else }}
      image:
        sharedGallery:
          gallery: {{ .Values.talos.imageName }}
          name: talos
          version: latest
      {{- end }}
      sshPublicKey: {{ if .Values.azure }}{{ default "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZLeGlkQ1FxTzZZU3JKUHpKNlNPa1loRk9yZVpSb0JCNlZPVlVGNEtHb1ogdGFsb3Mta2V5Cg==" .Values.azure.sshPublicKey }}{{ else }}c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZLeGlkQ1FxTzZZU3JKUHpKNlNPa1loRk9yZVpSb0JCNlZPVlVGNEtHb1ogdGFsb3Mta2V5Cg=={{ end }}
      disableExtensionOperations: {{ if and .Values.azure (hasKey .Values.azure "disableExtensionOperations") }}{{ .Values.azure.disableExtensionOperations }}{{ else }}true{{ end }}
      osDisk:
        diskSizeGB: {{ .Values.kommodity.controlplane.os.disk.size }}
        osType: Linux
        managedDisk:
          storageAccountType: {{ default "Premium_LRS" .Values.kommodity.controlplane.os.disk.type }}

{{- range $name, $np := .Values.kommodity.nodepools }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: {{ $.Release.Name }}-worker-{{ $name }}-{{ include "kommodity-cluster.machineSpecsHash" (dict "poolValues" $np "allValues" $.Values) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  template:
    spec:
      vmSize: {{ $np.sku }}
      {{- if dig "marketplace" "" $.Values.talos }}
      image:
        marketplace:
          publisher: {{ $.Values.talos.marketplace.publisher }}
          offer: {{ $.Values.talos.marketplace.offer }}
          sku: {{ $.Values.talos.marketplace.sku }}
          version: {{ $.Values.talos.marketplace.version }}
      {{- else if dig "computeGallery" "" $.Values.talos }}
      image:
        computeGallery:
          gallery: {{ $.Values.talos.computeGallery.gallery }}
          name: {{ $.Values.talos.computeGallery.name }}
          version: {{ $.Values.talos.computeGallery.version }}
          {{- if dig "computeGallery" "subscriptionID" "" $.Values.talos }}
          subscriptionID: {{ $.Values.talos.computeGallery.subscriptionID }}
          {{- end }}
          {{- if dig "computeGallery" "resourceGroup" "" $.Values.talos }}
          resourceGroup: {{ $.Values.talos.computeGallery.resourceGroup }}
          {{- end }}
      {{- else if dig "id" "" $.Values.talos }}
      image:
        id: {{ $.Values.talos.id }}
      {{- else }}
      image:
        sharedGallery:
          gallery: {{ $.Values.talos.imageName }}
          name: talos
          version: latest
      {{- end }}
      sshPublicKey: {{ if $.Values.azure }}{{ default "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZLeGlkQ1FxTzZZU3JKUHpKNlNPa1loRk9yZVpSb0JCNlZPVlVGNEtHb1ogdGFsb3Mta2V5Cg==" $.Values.azure.sshPublicKey }}{{ else }}c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZLeGlkQ1FxTzZZU3JKUHpKNlNPa1loRk9yZVpSb0JCNlZPVlVGNEtHb1ogdGFsb3Mta2V5Cg=={{ end }}
      disableExtensionOperations: {{ if and $.Values.azure (hasKey $.Values.azure "disableExtensionOperations") }}{{ $.Values.azure.disableExtensionOperations }}{{ else }}true{{ end }}
      osDisk:
        diskSizeGB: {{ $np.os.disk.size }}
        osType: Linux
        managedDisk:
          storageAccountType: {{ default "Premium_LRS" $np.os.disk.type }}
      {{- if $np.dataDisks }}
      dataDisks:
        {{- range $np.dataDisks }}
        - nameSuffix: {{ .nameSuffix }}
          diskSizeGB: {{ .diskSizeGB }}
          lun: {{ .lun }}
          managedDisk:
            storageAccountType: {{ default "Premium_LRS" .storageAccountType }}
          {{- if .cachingType }}
          cachingType: {{ .cachingType }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
