apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-cluster-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayCluster
    name: my-cluster
    namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      generateType: worker
      talosVersion: v1.11.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ScalewayCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  failureDomains:
  - fr-par-2
  projectID: "a76e6396-6a8e-4406-a1dc-ad4024c60295"
  region: fr-par
  scalewaySecretName: my-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster
  namespace: default
stringData:
  SCW_ACCESS_KEY: "SCWYHMHP60K2V7MPMF3Y"
  SCW_SECRET_KEY: "615eee66-5427-4aab-9e56-b19a54ff709b"
type: Opaque
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ScalewayMachineTemplate
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  template:
    spec:
      commercialType: DEV1-S
      image:
        name: talos-v1.11.0
      publicNetwork:
        enableIPv4: true
      rootVolume:
        size: 20
        type: block
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  clusterName: my-cluster
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talos-cluster-md-0
          namespace: default
      clusterName: my-cluster
      failureDomain: fr-par-2
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ScalewayMachineTemplate
        name: my-cluster-md-0
        namespace: default
      version: v1.33.4
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ScalewayMachineTemplate
metadata:
  name: my-cluster-md-0
  namespace: default
spec:
  template:
    spec:
      commercialType: DEV1-S
      image:
        name: talos-v1.11.0
      publicNetwork:
        enableIPv4: true
      rootVolume:
        size: 20
        type: block
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-cluster-control-plane
  namespace: default
spec:
  version: v1.33.4
  replicas: 1
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayMachineTemplate
    name: my-cluster-control-plane
    namespace: default
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.11.0
      hostname: {}
    init:
      generateType: ""
      hostname: {}
