version: "2"

linters:
  default: all
  disable:
    - depguard
    # Deprecated linters.
    - wsl
    # We may enable this in the future.
    - exhaustruct
    # Acting up with replace directives in go.mod
    - gomoddirectives
    # Kubernetes objects are all interface based
    - ireturn
  exclusions:
    rules:
      - path: "pkg/net/"
        linters: [revive]
        text: "avoid package names that conflict with Go standard library"
      - path: "pkg/ui/api/"
        linters: [revive]
        text: "avoid meaningless package names"
