version: "2"

linters:
  default: all
  disable:
    - depguard
    # Deprecated linters.
    - wsl
    # We may enable this in the future.
    - exhaustruct
    # Acting up with replace directives in go.mod
    - gomoddirectives
    # Kubernetes objects are all interface based
    - ireturn
