apiVersion: v1
kind: Config
clusters:
  - name: kommodity
    cluster:
      server: http://localhost:8443
      insecure-skip-tls-verify: true
users:
  - name: admin
    user:
      username: admin
      password: admin
contexts:
  - name: kommodity-context
    context:
      cluster: kommodity
      user: admin
current-context: kommodity-context
preferences: {}
