{{- if eq .Values.kommodity.provider.name "Docker" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: localhost
    port: 6443
{{- end }}
