{{- if eq .Values.kommodity.provider.name "Docker" }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ .Release.Name }}-controlplane
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
        cluster.x-k8s.io/deployment-name: {{ .Release.Name }}-controlplane
        app.kubernetes.io/managed-by: kommodity
    spec:
      customImage: ghcr.io/siderolabs/talos:{{ .Values.talos.version }}

{{- range $name, $np := .Values.kommodity.nodepools }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ $.Release.Name }}-worker-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ $.Release.Name }}
        cluster.x-k8s.io/deployment-name: {{ $.Release.Name }}-worker-{{ $name }}
        app.kubernetes.io/managed-by: kommodity
    spec:
      customImage: ghcr.io/siderolabs/talos:{{ $.Values.talos.version }}
{{- end }}
{{- end }}
