{{- if eq .Values.kommodity.provider.name "Docker" }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ .Release.Name }}-controlplane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      customImage: ghcr.io/siderolabs/talos:{{ .Values.talos.version }}

{{- range $name, $np := .Values.kommodity.nodepools }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ $.Release.Name }}-worker-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      customImage: ghcr.io/siderolabs/talos:{{ .Values.talos.version }}
{{- end }}
{{- end }}
