{{- if eq .Values.kommodity.provider.name "Kubevirt" }}
{{- $provider := dig "Kubevirt" (dict) .Values.kommodity.provider }}
{{- $config := dig "config" (dict) $provider }}
{{- $secret := dig "secret" (dict) $provider }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  infraClusterSecretRef:
    name: {{ dig "name" "" $secret }}
    namespace: {{ .Release.Namespace }}
  controlPlaneServiceTemplate:
    metadata:
      namespace: {{ dig "infraClusterNamespace" "" $config }}
      {{- with (dig "annotations" (dict) (dig "controlPlaneServiceTemplate" (dict) $config)) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      type: {{ dig "controlPlaneServiceTemplate" "spec" "type" "LoadBalancer" $config }}
  {{- if dig "controlPlaneEndpoint" "" $config }}
  controlPlaneEndpoint:
    host: {{ dig "controlPlaneEndpoint" "host" "" $config }}
    port: {{ dig "controlPlaneEndpoint" "port" 6443 $config }}
  {{- end }}
{{- end }}
