// Code generated by generate-scheme.sh; DO NOT EDIT.
//
//nolint
package provider

import (
    "k8s.io/apimachinery/pkg/runtime"
	scheme_1 "sigs.k8s.io/cluster-api/api/v1beta1"
	scheme_2 "github.com/siderolabs/cluster-api-bootstrap-provider-talos/api/v1alpha2"
	scheme_3 "github.com/siderolabs/cluster-api-bootstrap-provider-talos/api/v1alpha3"
	scheme_4 "github.com/siderolabs/cluster-api-control-plane-provider-talos/api/v1alpha3"
)

func addAllProvidersToScheme(scheme *runtime.Scheme) error {
    var err error
	if err = scheme_1.AddToScheme(scheme); err != nil { return err }
	if err = scheme_2.AddToScheme(scheme); err != nil { return err }
	if err = scheme_3.AddToScheme(scheme); err != nil { return err }
	if err = scheme_4.AddToScheme(scheme); err != nil { return err }
    return nil
}
