package libkapi //nolint:testpackage // exercises unexported internals: webhookCertDir, ensureSelfSignedWebhookCert

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestEnsureSelfSignedWebhookCert_GeneratesCert verifies that a missing
// certificate is generated at the expected, fixed file names.
//
//nolint:paralleltest // mutates the package-global webhookCertDir
func TestEnsureSelfSignedWebhookCert_GeneratesCert(t *testing.T) {
	withTempWebhookCertDir(t)

	err := ensureSelfSignedWebhookCert([]string{"localhost"})
	require.NoError(t, err)

	assert.FileExists(t, filepath.Join(webhookCertDir, webhookCertFileName))
	assert.FileExists(t, filepath.Join(webhookCertDir, webhookKeyFileName))
}

// TestEnsureSelfSignedWebhookCert_ReusesExistingCert is a regression test
// for the reuse-across-restarts requirement: a second call against the same
// directory must not overwrite the certificate generated by the first,
// since doing so would invalidate any caBundle already registered on a
// Validating/MutatingWebhookConfiguration.
//
//nolint:paralleltest // mutates the package-global webhookCertDir
func TestEnsureSelfSignedWebhookCert_ReusesExistingCert(t *testing.T) {
	withTempWebhookCertDir(t)

	err := ensureSelfSignedWebhookCert([]string{"localhost"})
	require.NoError(t, err)

	certPath := filepath.Join(webhookCertDir, webhookCertFileName)
	keyPath := filepath.Join(webhookCertDir, webhookKeyFileName)

	//nolint:gosec // test-only: certPath is built from t.TempDir(), not caller input
	firstCert, err := os.ReadFile(certPath)
	require.NoError(t, err)

	//nolint:gosec // test-only: keyPath is built from t.TempDir(), not caller input
	firstKey, err := os.ReadFile(keyPath)
	require.NoError(t, err)

	err = ensureSelfSignedWebhookCert([]string{"localhost"})
	require.NoError(t, err)

	//nolint:gosec // test-only: certPath is built from t.TempDir(), not caller input
	secondCert, err := os.ReadFile(certPath)
	require.NoError(t, err)

	//nolint:gosec // test-only: keyPath is built from t.TempDir(), not caller input
	secondKey, err := os.ReadFile(keyPath)
	require.NoError(t, err)

	assert.Equal(t, firstCert, secondCert, "expected the second call to reuse the existing certificate")
	assert.Equal(t, firstKey, secondKey, "expected the second call to reuse the existing key")
}

// withTempWebhookCertDir points the package-level webhookCertDir at a fresh
// t.TempDir() for the duration of the test, restoring it on cleanup. Not
// safe to use from a t.Parallel() test - webhookCertDir is shared
// process-wide state (see its own doc comment).
func withTempWebhookCertDir(t *testing.T) {
	t.Helper()

	original := webhookCertDir
	webhookCertDir = t.TempDir()

	t.Cleanup(func() { webhookCertDir = original })
}
