package libkapi

import (
	"bytes"
	"context"
	"time"

	corev1client "k8s.io/client-go/kubernetes/typed/core/v1"
)

const (
	// webhookCertRotationInterval is how often each replica checks whether
	// the shared webhook cert Secret is due for renewal.
	webhookCertRotationInterval = 1 * time.Hour

	// webhookCertRenewalWindow is how long before a certificate's NotAfter
	// it's considered due for renewal. Certificates generated by
	// certutil.GenerateSelfSignedCertKey are valid for 365 days, so a
	// 30-day window leaves ample time for every replica to notice and
	// converge before expiry.
	webhookCertRenewalWindow = 30 * 24 * time.Hour
)

// runWebhookCertRotationLoop periodically checks whether the shared webhook
// cert Secret is due for renewal, until ctx is done. Started once, right
// after the initial sync succeeds, bound to ListenAndServe's
// internalHooksCtx - the same lifetime already used for other
// server-lifetime background work (see its own doc on the Server struct).
func (s *Server) runWebhookCertRotationLoop(ctx context.Context) {
	client, err := s.newCoreV1Client("webhook cert rotation")
	if err != nil {
		s.logger.Error("Failed to start webhook certificate rotation loop", "error", err)

		return
	}

	ticker := time.NewTicker(webhookCertRotationInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			s.reconcileWebhookCert(ctx, client)
		}
	}
}

// reconcileWebhookCert renews the shared webhook cert Secret if it's due,
// and - if the winning certificate differs from what's currently on disk -
// rewrites the local files so controller-runtime's own certwatcher picks it
// up live.
func (s *Server) reconcileWebhookCert(ctx context.Context, client corev1client.CoreV1Interface) {
	certPEM, keyPEM, err := RenewWebhookCertIfDue(
		ctx, client, s.webhookCfg.DNSNames, s.systemNamespace, DefaultWebhookCertSecretName,
		webhookCertRenewalWindow, time.Now)
	if err != nil {
		s.logger.Error("Failed to reconcile webhook certificate", "error", err)

		return
	}

	if bytes.Equal(s.WebhookCABundle(), certPEM) {
		return
	}

	err = writeWebhookCertFiles(certPEM, keyPEM)
	if err != nil {
		s.logger.Error("Failed to write rotated webhook certificate to disk", "error", err)

		return
	}

	s.setWebhookCABundle(certPEM)

	s.logger.Info("Webhook certificate rotated")
}
