#!/usr/bin/env bash

providers_yaml="pkg/provider/providers.yaml"
output_file="pkg/provider/scheme.go"

cat > "$output_file" <<EOF
// Code generated by generate-scheme.sh; DO NOT EDIT.
//
//nolint
package provider

import (
    "k8s.io/apimachinery/pkg/runtime"
    "k8s.io/apimachinery/pkg/runtime/schema"

EOF

# Extract all scheme_locations with their go_module or repository and generate import aliases
yq -r '.providers[] | (.go_module // .repository) as $base | .scheme_locations[] | $base + "/" + .' "$providers_yaml" | \
  awk '{ alias="scheme_" NR; printf "\t%s \"%s\"\n", alias, $0 }' >> "$output_file"

cat >> "$output_file" <<EOF
)

func addAllProvidersToScheme(scheme *runtime.Scheme) error {
    var err error
EOF


# Generate AddToScheme calls for each import alias
yq -r '.providers[].scheme_locations[]' "$providers_yaml" | \
  awk '{ alias="scheme_" NR; printf "\tif err = %s.AddToScheme(scheme); err != nil { return err }\n", alias }' >> "$output_file"

cat >> "$output_file" <<EOF
    return nil
}
EOF

cat >> "$output_file" <<EOF

func GetProviderGroupKindVersions() []schema.GroupVersion {
  return []schema.GroupVersion{
EOF


yq -r '.providers[] | (.go_module // .repository) as $base | .scheme_locations[] | $base + "/" + .' "$providers_yaml" | \
  awk '{ alias="scheme_" NR; printf "\t\t%s.GroupVersion,\n", alias }' >> "$output_file"

cat >> "$output_file" <<EOF
  }
}
EOF