#!/usr/bin/env bash

providers_yaml="pkg/provider/providers.yaml"
output_file="pkg/config/provider.go"

cat > "$output_file" <<EOF
// Code generated by generate-provider-consts.sh; DO NOT EDIT.
//
//nolint
package config

// Provider represents an infrastructure provider.
type Provider string

const (
EOF

# Generate a unique list of providers
unique_providers=()
for provider in $(yq -r '.providers[].provider' "$providers_yaml"); do
  if [[ ! " ${unique_providers[@]} " =~ " ${provider} " ]]; then
    unique_providers+=("$provider")
  fi
done

for provider in "${unique_providers[@]}"; do
  # Use provider name as constant name, capitalize first letter
  const_name="Provider$(echo $provider | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
  echo -e "\t$const_name Provider = \"$provider\"" >> "$output_file"
done

cat >> "$output_file" <<EOF
)

// GetAllProviders returns a list of all supported providers without local development providers.
func GetAllProviders() []Provider {
	return []Provider{
EOF
for provider in "${unique_providers[@]}"; do
  const_name="Provider$(echo $provider | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
  echo -e "		$const_name," >> "$output_file"
done
cat >> "$output_file" <<EOF
	}
}
EOF
