basePath: /api
definitions:
  api.ClusterHealthResponse:
    properties:
      healthy:
        type: boolean
      reason:
        type: string
    type: object
info:
  contact: {}
  description: API endpoints for Kommodity UI.
  title: Kommodity UI API
  version: 0.1.0
paths:
  /api/cluster/{clusterName}/health:
    get:
      parameters:
      - description: Name of the cluster to check health for
        in: path
        name: clusterName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ClusterHealthResponse'
        "400":
          description: If the cluster name is missing or invalid
          schema:
            type: string
        "500":
          description: If there is a server error
          schema:
            type: string
      summary: Checks the health of a cluster by accessing its /livez endpoint.
      tags:
      - UI
      - Info
      - Health
  /api/info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: If there is a server error
          schema:
            type: string
      summary: Obtain Kommodity system information
      tags:
      - UI
      - Info
schemes:
- https
swagger: "2.0"
