---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cabpt-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-bootstrap-cluster-x-k8s-io-v1alpha3-talosconfig
    failurePolicy: Fail
    name: vtalosconfig.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - talosconfigs
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-bootstrap-cluster-x-k8s-io-v1alpha3-talosconfigtemplate
    failurePolicy: Fail
    name: vtalosconfigtemplate.cluster.x-k8s.io
    rules:
      - apiGroups:
          - bootstrap.cluster.x-k8s.io
        apiVersions:
          - v1alpha3
        operations:
          - UPDATE
        resources:
          - talosconfigtemplates
    sideEffects: None
