---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cacppt-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-controlplane-cluster-x-k8s-io-v1alpha3-taloscontrolplane
    failurePolicy: Fail
    name: validate.taloscontrolplane.controlplane.cluster.x-k8s.io
    rules:
      - apiGroups:
          - controlplane.cluster.x-k8s.io
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - taloscontrolplanes
    sideEffects: None
